### ISSUE TITLE
Retrieve Energy Values (Consumption)

### ISSUE THREAD

**Issue by zoernert** [claudiospizzi/node-red-contrib-mystrom-switch#7]
Is it possible to get a consumption information within your Node-RED module? If so, I would like to build a new sample Flow in addition using your and our module: https://github.com/energychain/node-red-contrib-stromquittung . But I do not have a MyStrom-Switch here to test :/

**Comment by claudiospizzi** [comment]
Hi. The MyStrom Switch delivers the following details on the local api via [http://192.168.1.x/report](http://192.168.1.x/report):

```json
{
"power": 0,
"Ws": 0,
"relay": false,
"temperature": 25.5
}
```

So we only have the current power in Watt. The power can be read with the MyStrom Switch Status node. Does that help or is sufficient? The node does not show the consumption over all.

**Comment by stilicrafter** [comment]
> {
"power": 0,
"Ws": 0,
"relay": false,
"temperature": 25.5
}So we only have the current power in Watt

Ws are the WattSeconds. The MyStromSwitch saves the sum of WattSeconds consumed since the last request.
If you add / sum the values that accumulats over for example a day, you get the consumtion of the whole day.


You can also convert from WattSeconds to the often used WattStunden.
